### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by jimdigriz** [portier/demo-rp#15]
I am trying to create a demo using https://broker.portier.io but as it has no [CORS headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) on `/.well-known/openid-configuration` or `/keys.json` I am unable to have a browser show the magic. :)

Maybe this is deliberate though with the view to keep the access token out of the hands of any JavaScript?

**Comment by stephank** [comment]
Browsers normally have no reason to fetch those resources. What kind of demo are you building that you need access from the browser? Is it a regular login demo, or some visualisation of how Portier works, or something else maybe?

While I don't think opening up those two *specific* resources is an issue, I also think we need to properly motivate this kind of change. Especially because CORS is a security mechanism. Otherwise, we'll have a piece of code in the broker somewhere that maybe we don't really understand anymore at some point in the future. (We already have a bunch of those things, unfortunately.)

**Comment by jimdigriz** [comment]
You are quite right, I was looking for a public OAuth2 endpoint that would dish out an `access_token` and then I could use against a UserInfo endpoint; Portier only returns an `id_token` which is not useful for my needs.  Sorry for wasting your time.

FYI, demo project is https://gitlab.com/jimdigriz/oauth2-worker
