### ISSUE TITLE
Handle errors returned from the broker

### ISSUE THREAD

**Issue by stephank** [portier/demo-rp#7]
The broker may call back with `error` and `error_description` parameters, see [the OAuth2 spec](https://tools.ietf.org/html/rfc6749#section-4.1.2.1).

See also the implementation in the broker in https://github.com/portier/portier-broker/pull/40.

**Comment by callahad** [comment]
Fixed in 1e31c2488e809038d660daf6e113301c32d17b34

**Comment by callahad** [comment]
Not merging 1e31c2488e809038d660daf6e113301c32d17b34 yet -- we're not sure exactly how we're supposed to handle this. Let's hash it out:

Two quotes from the [OAuth2 Spec](https://tools.ietf.org/html/rfc6749#section-4.1.2.1):

> If the request fails due to a missing, invalid, or mismatching redirection URI, or if the client identifier is missing or invalid, the authorization server SHOULD inform the resource owner of the error and MUST NOT automatically redirect the user-agent to the invalid redirection URI.

So if the Client ID or Redirect URI are bad, we:
- SHOULD inform the "resource owner" (the user).
- MUST NOT redirect to the Redirect URI.

> If the resource owner denies the access request or if the request fails for reasons other than a missing or invalid redirection URI, the authorization server informs the client by adding the following parameters to the query component of the redirection URI using the "application/x-www-form-urlencoded" format

If anything else goes wrong, we:
- Inform the client (the RP) via data in the query string.
- (Presumably) redirect to the Redirect URI per normal.

**Comment by callahad** [comment]
This sounds to me like:
- In the first case, the Broker should show an error message directly.
- In the second case, the Broker should return the error message to the RP.

Which leaves open the question of _how_ the Broker returns the message to the RP. The OAuth2 spec, as I understand it, only supports returning things as query params of a GET request.

However, the Broker implements two extensions to the OAuth2 spec:
- [OAuth2 Multiple Response Types](http://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#id_token) which also defines `query` and `fragment` response modes and states that, for `id_token` responses:
  
  > The default Response Mode for this Response Type is the fragment encoding and the query encoding MUST NOT be used. Both successful and error responses SHOULD be returned using the supplied Response Mode, or if none is supplied, using the default Response Mode.
  
  So we should use the [fragment encoding](http://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#ResponseModes) by default, unless otherwise specified. We should not use the query param encoding.
- [OAuth2 Form Post Response Mode](http://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html), which defines the `form_post` response mode. This is the only response mode supported by the Broker, and it is requested by compliant RPs.

To me, this indicates that this RP is correctly implementing the spec: errors should be returned by POSTing them back to the Redirect URI as form data. This may require updates to the Broker.
